# Generated by Django 6.0 on 2026-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminprofile_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(default='student@school.com', max_length=30),
            preserve_default=False,
        ),
    ]
