# Generated by Django 6.0.2 on 2026-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_photo_student_profile_pic_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='MCA', max_length=100),
            preserve_default=False,
        ),
    ]
